---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-crawler-prod
  labels:
    app: search-engine-prod
    component: search-engine-crawler-prod
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30812
  selector:
    app: search-engine-prod
    component: search-engine-crawler-prod

