---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: monitoring
    component: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: monitoring
    component: grafana

