---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: logging
    component: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 30601
  selector:
    app: logging
    component: kibana

