---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-crawler-stage
  labels:
    app: search-engine-stage
    component: search-engine-crawler-stage
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30802
  selector:
    app: search-engine-stage
    component: search-engine-crawler-stage

