version: '3'
services:

  fluentd:
    build:
      context: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    links:
      - "elasticsearch"
    networks:
      docker:
        ipv4_address: 10.5.0.12
        aliases:
          - fluentd

  search_engine_ui:
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.5.0.12:24224
        tag: search_engine_ui

  search_engine_crawler:
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.5.0.12:24224
        tag: search_engine_crawler

  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    volumes:
      - volume_search_engine_elasticsearch:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      docker:
        ipv4_address: 10.5.0.13
        aliases:
          - elasticsearch

  kibana:
    image: kibana:7.4.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      docker:
        ipv4_address: 10.5.0.14
        aliases:
          - kibana

volumes:
  volume_search_engine_elasticsearch:

networks:
  docker:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
