---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-ui-stage
  labels:
    app: search-engine-stage
    component: search-engine-ui-stage
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30801
  selector:
    app: search-engine-stage
    component: search-engine-ui-stage
