---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-prod
  labels:
    app: search-engine-prod
    component: rabbitmq-prod
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
      name: rabbit
    - port: 15672
      protocol: TCP
      targetPort: 15672
      name: rabbit-management
  selector:
    app: search-engine-prod
    component: rabbitmq-prod
