---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-bot
  labels:
    app: monitoring
    component: alertmanager-bot
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: monitoring
    component: alertmanager-bot

