apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: monitoring
    component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
      component: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: monitoring
        component: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.39.1
          name: prometheus
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          env:
            - name: TZ
              value: "Europe/Moscow"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-config
              mountPath: /etc/prometheus/alert.rules
              subPath: alert.rules
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

