---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: search-engine
    component: mongodb
#    post-db: "true"
#    comment-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: search-engine
        component: mongodb
#        post-db: "true"
#        comment-db: "true"
    spec:
      containers:
        - image: mongo:3.2
          name: mongodb
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          emptyDir: {}
#          volumeMounts:
#            - name: mongo-gce-pd-storage
#              mountPath: /data/db
#      volumes:
#        - name: mongo-gce-pd-storage
#          persistentVolumeClaim:
#            claimName:  mongo-pvc