---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-prod
  labels:
    app: search-engine-prod
    component: mongodb-prod
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: search-engine-prod
    component: mongodb-prod

