---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine-crawler
  labels:
    app: search-engine
    component: search-engine-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: search-engine-crawler
  template:
    metadata:
      name: search-engine-crawler
      labels:
        app: search-engine
        component: search-engine-crawler
    spec:
      containers:
        - image: astrviktor/search_engine_crawler:0.1.0
          name: search-engine-crawler
          env:
            - name: MONGO
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
            - name: RMQ_HOST
              value: "rabbitmq"
            - name: RMQ_QUEUE
              value: "queue"
            - name: RMQ_USERNAME
              value: "rabbit_user0"
            - name: RMQ_PASSWORD
              value: "rabbit_pass0"
            - name: EXCLUDE_URLS
              value: ".*github.com"
            - name: URL
              value: "https://vitkhab.github.io/search_engine_test_site/"

