---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-ui
  labels:
    app: search-engine
    component: search-engine-ui
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: search-engine
    component: search-engine-ui

