---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-ui-prod
  labels:
    app: search-engine-prod
    component: search-engine-ui-prod
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30811
  selector:
    app: search-engine-prod
    component: search-engine-ui-prod
