apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: '5s'
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets:
              - 'localhost:9090'
    
      - job_name: 'search-engine-crawler-stage'
        static_configs:
          - targets:
              - 'search-engine-crawler-stage.stage.svc.cluster.local:8000'
    
      - job_name: 'search-engine-ui-stage'
        static_configs:
          - targets:
              - 'search-engine-ui-stage.stage.svc.cluster.local:8000'
    

      - job_name: 'search-engine-crawler-prod'
        static_configs:
          - targets:
              - 'search-engine-crawler-prod.prod.svc.cluster.local:8000'
    
      - job_name: 'search-engine-ui-prod'
        static_configs:
          - targets:
              - 'search-engine-ui-prod.prod.svc.cluster.local:8000'


      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - 'node-exporter:9100'
    
    rule_files:
      - 'alert.rules'
    
    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
            - targets:
                - "alertmanager:9093"

  alert.rules: |
    groups:
      - name: test
        rules:
          - alert: PrometheusTargetMissing
            expr: up == 0
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: "Prometheus target missing (instance {{ $labels.instance }})"
              description: "A Prometheus target has disappeared. An exporter might be crashed. VALUE = {{ $value }}  LABELS: {{ $labels }}"

