---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: monitoring
    component: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30090
  selector:
    app: monitoring
    component: prometheus

